// <auto-generated />
using System;
using AssetTracking_EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTracking_EF.Migrations
{
    [DbContext(typeof(AssetTrackingDbContext))]
    [Migration("20260716133927_FourthMigration")]
    partial class FourthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetTracking_EF.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LocalCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Sweden",
                            Currency = "SEK",
                            Name = "Sweden Office"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Currency = "USD",
                            Name = "USA Office"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Currency = "EUR",
                            Name = "Germany Office"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Turkey",
                            Currency = "TRY",
                            Name = "Turkey Office"
                        });
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Computer", b =>
                {
                    b.HasBaseType("AssetTracking_EF.Models.Asset");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Laptop", b =>
                {
                    b.HasBaseType("AssetTracking_EF.Models.Asset");

                    b.HasDiscriminator().HasValue("Laptop");
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Phone", b =>
                {
                    b.HasBaseType("AssetTracking_EF.Models.Asset");

                    b.HasDiscriminator().HasValue("MobilePhone");
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Tablet", b =>
                {
                    b.HasBaseType("AssetTracking_EF.Models.Asset");

                    b.HasDiscriminator().HasValue("Tablet");
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Asset", b =>
                {
                    b.HasOne("AssetTracking_EF.Models.Office", "Office")
                        .WithMany("Assets")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("AssetTracking_EF.Models.Office", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
